# fly.toml app configuration file generated for stockscreener-ahjvjg on 2025-09-08T20:59:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stockscreener-ahjvjg'
primary_region = 'fra'

[experimental]
  auto_rollback = true

[deployment]
  strategy = "recreate"

[build]

[processes]
  app = 'npm start'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
