app = "stockscreener-ahjvjg"
primary_region = "fra"

[build]
  # авто-білд для Node, Dockerfile не потрібен

[processes]
  app = "npm start"  # у тебе це "node app.js"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

[experimental]
  auto_rollback = true
